package com.recomm.model.domain.application.entity;
// Generated Jan 7, 2019 10:43:39 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import com.recomm.model.domain.application.interfaces.ILogs;

/**
 * User generated by hbm2java
 */
@Entity
@Table
(
    name = "logs",
    catalog = "rlapi",
    uniqueConstraints = @UniqueConstraint
    (
        columnNames = "idlogs"
    )
)
public class Logs implements ILogs, Serializable
{
     @GeneratedValue (strategy = GenerationType.AUTO)
     @Basic (optional = false)
     @Column (name = "idLogs", nullable = false)
     @Id
     private int idLogs;

     @Column (name = "users", nullable = false)
     private int users = 2;

     @Column (name = "clientip", nullable = false, length = 50)
     private String clientip = "0.0.0.0";

     @Column (name = "transactionId", nullable = false, length = 50)
     private String transactionId = "0";

     @Column (name = "authCode", nullable = false, length = 50)
     private String authCode = "none";

     @Column (name = "amount", nullable = false, length = 50)
     private String amount = "0.00";

     @Column (name = "customerId", nullable = false, length = 50)
     private String customerId = "0";

     @Column (name = "errorCode", nullable = false, length = 50)
     private String errorCode = "";

     @Column (name = "errorType", nullable = false, length = 10)
     private String errorType = "";

     @Column (name = "errorMsg", nullable = false, length = 80)
     private String errorMsg = "";

     @Column (name = "logText", nullable = false, length = 4096)
     private String logText = "";

     @Column (name = "errorSource", nullable = false, length = 80)
     private String errorSource = "";

     @Temporal (TemporalType.TIMESTAMP)
     @Column (name = "creation", nullable = false, length = 19)
     private Date logDate;

    public Logs()
    {
    }

    public Logs (Integer idLogs)
    {
        this.idLogs = idLogs;
    }

    public Logs (int idLogs, String transactionId, String customerId, Date logDate)
    {
        this.idLogs = idLogs;
        this.transactionId = transactionId;
        this.customerId = customerId;
        this.logDate = logDate;
    }

    public Logs (int idLogs,
                 int users,
                 String clientip,
                 String transactionId,
                 String authCode,
                 String amount,
                 String customerId,
                 String errorCode,
                 String errorType,
                 String errorMsg,
                 String logText,
                 String errorSource,
                 Date logDate
                )
    {
       this.idLogs = idLogs;
       this.users = users;
       this.clientip = clientip;
       this.transactionId = transactionId;
       this.authCode = authCode;
       this.amount = amount;
       this.customerId = customerId;
       this.errorCode = errorCode;
       this.errorType = errorType;
       this.logDate = logDate;
       this.errorMsg = errorMsg;
       this.logText = logText;
       this.errorSource = errorSource;
       this.logDate = logDate;
    }

    /**
     * @return the clientip
     */
    @Override
    public String getClientip()
    {
        return clientip;
    }

    /**
     * @param clientip the clientip to set
     */
    @Override
    public void setClientip (String clientip)
    {
        this.clientip = clientip;
    }

    /**
     * @return the authCode
     */
    @Override
    public String getAuthCode()
    {
        return authCode;
    }

    /**
     * @param authCode the authCode to set
     */
    @Override
    public void setAuthCode (String authCode)
    {
        this.authCode = authCode;
    }

    /**
     * @return the amount
     */
    @Override
    public String getAmount()
    {
        return amount;
    }

    /**
     * @param amount the amount to set
     */
    @Override
    public void setAmount (String amount)
    {
        this.amount = amount;
    }

    @Override
    public int getUsers()
    {
        return this.users;
    }

    @Override
    public void setUsers (int users)
    {
        this.users = users;
    }

    /**
     * @return the transactionId
     */
    @Override
    public String getTransactionId()
    {
        return transactionId;
    }

    /**
     * @param transactionId the transactionId to set
     */
    @Override
    public void setTransactionId (String transactionId)
    {
        this.transactionId = transactionId;
    }

    /**
     * @return the customerId
     */
    @Override
    public String getCustomerId()
    {
        return customerId;
    }

    /**
     * @param customerId the customerId to set
     */
    @Override
    public void setCustomerId (String customerId)
    {
        this.customerId = customerId;
    }

    /**
     * @return the errorCode
     */
    @Override
    public String getErrorCode()
    {
        return errorCode;
    }

    /**
     * @param errorCode the errorCode to set
     */
    @Override
    public void setErrorCode (String errorCode)
    {
        this.errorCode = errorCode;
    }

    /**
     * @return the errorType
     */
    @Override
    public String getErrorType()
    {
        return errorType;
    }

    /**
     * @param errorType the errorType to set
     */
    @Override
    public void setErrorType (String errorType)
    {
        this.errorType = errorType;
    }

    /**
     * @return the errorMsg
     */
    @Override
    public String getErrorMsg()
    {
        return errorMsg;
    }

    /**
     * @param errorMsg the errorMsg to set
     */
    @Override
    public void setErrorMsg (String errorMsg)
    {
        this.errorMsg = errorMsg;
    }

    /**
     * @return the logText
     */
    @Override
    public String getLogText()
    {
        return logText;
    }

    /**
     * @param logText the logText to set
     */
    @Override
    public void setLogText (String logText)
    {
        this.logText = logText;
    }

    /**
     * @return the errorSource
     */
    @Override
    public String getErrorSource()
    {
        return errorSource;
    }

    /**
     * @param errorSource the errorSource to set
     */
    @Override
    public void setErrorSource (String errorSource)
    {
        this.errorSource = errorSource;
    }

    @Override
    public int getIdLogs()
    {
        return this.idLogs;
    }

    @Override
    public void setIdLogs (int idLogs)
    {
        this.idLogs = idLogs;
    }

    @Override
    public Date getLogDate()
    {
        return this.logDate;
    }

    @Override
    public void setLogDate (Date logDate)
    {
        this.logDate = logDate;
    }
}
